# Generated by Django 2.1.1 on 2018-10-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eimage',
            field=models.ImageField(null=True, upload_to='emp'),
        ),
    ]
